### PR TITLE
Add pointer to new elementsproject.org repository.

### PR DESCRIPTION
**Pull request by wintercooled**
Added link to new repository for the https://elementsproject.org website.

### CODE REVIEW

**Comment by wintercooled** [comment]
@wtogami Could you review/merge/request someone else does please to prevent people logging Issues or Pull Requests against this reposiroty as opposed to the https://github.com/ElementsProject/elementsproject.github.io one. Thanks.

**Comment by martindale** [comment]
:confused: — which URL should be considered the canonical resource for Elements, and why is the repository moving?

**Comment by instagibbs** [comment]
@martindale IIRC there was hesitancy to nuke the old repo yet a desire to start fresh, thanks to the efforts of @wintercooled

**Comment by wintercooled** [comment]
@martindale The URL remains the same for the site: https://elementsproject.org and the new repository is mentioned in this PR (https://github.com/ElementsProject/elementsproject.github.io). 

I'm trying to respond in a timely manner to Issues and Pull Requests in the new repo and the tutorial section is part of a focus on trying to promote new community developer involvement, so I thought this PR was needed in case people logged issues etc here and not there now. Thanks, Matt.

**Comment by martindale** [comment]
If you're going to switch repos (something I strongly recommend against), some of the accumulated value can be re-captured by first renaming this repo, then renaming the new repo to `elementsproject.org`.  You'll still lose all of your followers and forks, however.

**Comment by wintercooled** [comment]
The choice of migrating to the more popular Jekyll platform, as used by GitHub Pages, dictated the naming convention of the new repository.

**Comment by maaku** [comment]
What @martindale is saying is that you can rename repositories. It's a setting in the configuration of the repo. It's considered better practice because it doesn't invalidate all the forks and stars and issues and pull requests and discussions of the old/existing repo.

**Comment by wintercooled** [comment]
Unfortunately, repositories using GitHub pages must be created with (and then continue to use) the naming convention: name.github.io, so renaming the existing repository would not have worked.

**Comment by maaku** [comment]
FWIW I'm pretty sure that isn't true, having setup many GitHub pages myself which are not name.github.io and work just fine. User or organization pages are auto-detected from that exact naming scheme, but you can configure any repo to have a `gh-pages` branch, and set that branch as the default if you want. Since it is a custom domain site, you just need to set CNAME in the settings and/or add a CNAME and configure the DNS, and it will serve just fine. There's more information at the Github pages help:

https://help.github.com/articles/user-organization-and-project-pages/

**Comment by wintercooled** [comment]
Yes, it was created as a user and organization pages site, not a project site.

The old site was not active in terms of maintenance but yes, some people may still have been actively following it so agree that's a downside and noted for future reference.

**Pull request closed without merging**
