### PR TITLE
Add Confidential Transactions Presentation

### PR DESCRIPTION
**Pull request by martindale**
This adds Greg's latest presentation on Confidential Transactions to the index of the CT subsite.  [preview](https://test.elementsproject.org/elements/confidential-transactions/)

### CODE REVIEW

**Comment by gmaxwell** [comment]
ACK.

**Comment by bgorlick** [comment]
NACK -- This is nearly perfect, but the first string of code in the code sample runs off the edge of the page, and there is no scrollbar allowing you to scroll to the right. I am referring to this line in particular, at least on my screen TX=`elements-cli createrawtransaction '[{"txid": "421079661b117b659af3431096ce2118043396e3647e523e413cd626fa798df7", "vout": 0, "nValue": 0.001}, {"txid": "17aa26d29582a9a26f020

**Comment by martindale** [comment]
@bgorlick change is unrelated; if you could file another issue we can get that fixed on `master`.  Merging on above ACK.

**Comment by bgorlick** [comment]
You're right, my mistake, will file new issue.

**Pull request merged**
